"""empty message

Revision ID: 34ce7a878feb
Revises: d5cdd0c5fce9
Create Date: 2024-07-27 22:56:26.470385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ce7a878feb'
down_revision = 'd5cdd0c5fce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('created', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('created', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('edited', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('diameter')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_class', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('cost_in_credits', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('crew', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('max_atmosphering_speed', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('cargo_capacity', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('created', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('consumables')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('max_atmosphering_speed')
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('vehicle_class')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('gravity')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
